/* Generated By:JavaCC: Do not edit this line. YakaConstants.java */
public interface YakaConstants {

  int EOF = 0;
  int BOOLEEN = 8;
  int VAR = 9;
  int FAIRE = 10;
  int SINON = 11;
  int POUR = 12;
  int SI = 13;
  int FSI = 14;
  int ENTIER = 15;
  int RETOURNE = 16;
  int VRAI = 17;
  int TANTQUE = 18;
  int CONST = 19;
  int FAUX = 20;
  int FAIT = 21;
  int OU = 22;
  int ET = 23;
  int NON = 24;
  int FONCTION = 25;
  int FFONCTION = 26;
  int PROGRAMME = 27;
  int FPROGRAMME = 28;
  int PRINCIPAL = 29;
  int FPRINCIPAL = 30;
  int ALORS = 31;
  int ECRIRE = 32;
  int LIRE = 33;
  int ALALIGNE = 34;
  int PLUS = 35;
  int MOINS = 36;
  int MUL = 37;
  int DIV = 38;
  int INF = 39;
  int SUP = 40;
  int INFE = 41;
  int SUPE = 42;
  int DIFF = 43;
  int EGAL = 44;
  int ERREUR = 45;
  int chiffre = 46;
  int entier = 47;
  int lettre = 48;
  int ident = 49;
  int chaine = 50;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(*\"",
    "<token of kind 6>",
    "\"*)\"",
    "\"BOOLEEN\"",
    "\"VAR\"",
    "\"FAIRE\"",
    "\"SINON\"",
    "\"POUR\"",
    "\"SI\"",
    "\"FSI\"",
    "\"ENTIER\"",
    "\"RETOURNE\"",
    "\"VRAI\"",
    "\"TANTQUE\"",
    "\"CONST\"",
    "\"FAUX\"",
    "\"FAIT\"",
    "\"OU\"",
    "\"ET\"",
    "\"NON\"",
    "\"FONCTION\"",
    "\"FFONCTION\"",
    "\"PROGRAMME\"",
    "\"FPROGRAMME\"",
    "\"PRINCIPAL\"",
    "\"FPRINCIPAL\"",
    "\"ALORS\"",
    "\"ECRIRE\"",
    "\"LIRE\"",
    "\"ALALIGNE\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"=\"",
    "\"ERREUR\"",
    "<chiffre>",
    "<entier>",
    "<lettre>",
    "<ident>",
    "<chaine>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
  };

}
